### ISSUE TITLE
It hasn't been updated for over a half year.

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-en#22]
I just noticed today.

![image](https://user-images.githubusercontent.com/518808/152146935-b7ace695-e83a-45dc-8318-e23e929f25fb.png)

**Comment by k-takata** [comment]
GHA workflow will be automatically disabled if there are no changes in the repository for 60 days.
I thought this won't happen in this repository because the gh-pages branch will be automatically updated within 60 days.
However, that was wrong. If the default branch was not updated for 60 days, the workflow will be disabled.

A possible workaround is adding an empty commit to the master branch when the gh-pages branches has any changes.

**Comment by k-takata** [comment]
I think this has been fixed in #24. Closing.

**Comment by h-east** [comment]
Last commit was 2022-02-03...

**Comment by k-takata** [comment]
It seems that the `gh-pages` branch is correctly updated:
https://vim-jp.org/vimdoc-en/version9.html
![image](https://user-images.githubusercontent.com/840186/179687435-824f5d51-a55a-47cb-b49c-1c49abcf8bc2.png)

**Comment by h-east** [comment]
Ah, I was looking at the master branch. sorry.:bow:
